org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
# Холодный старт сборки и меньше работы dex-оптимизатора на устройстве
org.gradle.caching=true
org.gradle.parallel=true
kotlin.incremental=true
org.gradle.java.home=/opt/homebrew/opt/openjdk@17

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
